// Command mergenotices merges Go and frontend license inventories into THIRD_PARTY_NOTICES.md.
// Does not import application runtime packages.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

type goReport struct {
	GeneratedAt string `json:"generated_at"`
	ModuleCount int    `json:"module_count"`
	Entries     []struct {
		Module  string `json:"module"`
		Version string `json:"version"`
		Direct  bool   `json:"direct"`
		License string `json:"license"`
	} `json:"entries"`
	Summary map[string]int `json:"summary_by_license"`
}

type npmPackage struct {
	Licenses string `json:"licenses"`
	Repository string `json:"repository"`
	Publisher string `json:"publisher"`
}

func main() {
	repo := flag.String("repo", ".", "repository root")
	out := flag.String("out", "THIRD_PARTY_NOTICES.md", "output markdown path")
	flag.Parse()

	repoRoot := filepath.Clean(*repo)
	invDir := filepath.Join(repoRoot, "compliance", "inventory")
	goPath := filepath.Join(invDir, "go-modules.json")
	fePath := filepath.Join(invDir, "frontend-packages.json")

	goData, err := os.ReadFile(goPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "mergenotices: read %s: %v\n", goPath, err)
		os.Exit(1)
	}
	var goRep goReport
	if err := json.Unmarshal(goData, &goRep); err != nil {
		fmt.Fprintf(os.Stderr, "mergenotices: parse go inventory: %v\n", err)
		os.Exit(1)
	}

	feData, _ := os.ReadFile(fePath)
	fePackages := map[string]npmPackage{}
	if len(feData) > 0 {
		if err := json.Unmarshal(feData, &fePackages); err != nil {
			fmt.Fprintf(os.Stderr, "mergenotices: parse frontend inventory: %v\n", err)
			os.Exit(1)
		}
	}

	md := renderNotices(repoRoot, goRep, fePackages)
	outPath := filepath.Join(repoRoot, *out)
	if err := os.WriteFile(outPath, []byte(md), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "mergenotices: write: %v\n", err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "wrote %s\n", outPath)
}

func renderNotices(repoRoot string, goRep goReport, fePackages map[string]npmPackage) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Third-Party Notices\n\n")
	fmt.Fprintf(&b, "> Auto-generated by `scripts/license/generate-inventory.ps1`. Do not edit manually.\n")
	fmt.Fprintf(&b, "> Regenerate before each release. This file is **not** legal advice.\n\n")
	fmt.Fprintf(&b, "| Field | Value |\n|---|---|\n")
	fmt.Fprintf(&b, "| Generated (UTC) | %s |\n", time.Now().UTC().Format(time.RFC3339))
	fmt.Fprintf(&b, "| Go modules | %d |\n", goRep.ModuleCount)
	fmt.Fprintf(&b, "| npm packages (production) | %d |\n\n", len(fePackages))

	fmt.Fprintf(&b, "## Go Dependencies\n\n")
	fmt.Fprintf(&b, "Inventory: `compliance/inventory/go-modules.json`\n\n")
	writeGroupedGo(&b, goRep)

	fmt.Fprintf(&b, "## Frontend Dependencies (production bundle)\n\n")
	fmt.Fprintf(&b, "Inventory: `compliance/inventory/frontend-packages.json`\n\n")
	writeGroupedNPM(&b, fePackages)

	fmt.Fprintf(&b, "## Bundled Assets\n\n")
	fmt.Fprintf(&b, "| Asset | Path | License |\n|---|---|---|\n")
	fmt.Fprintf(&b, "| Nunito font | `frontend/src/assets/fonts/OFL.txt` | OFL-1.1 |\n")
	fmt.Fprintf(&b, "| App icon | `build/appicon.png` | go-stock |\n\n")

	fmt.Fprintf(&b, "## Runtime Platform Dependencies (not in SBOM)\n\n")
	fmt.Fprintf(&b, "- **Microsoft WebView2 Runtime** — required on Windows (Wails). See [WebView2 redistribution terms](https://developer.microsoft.com/microsoft-edge/webview2/).\n")
	fmt.Fprintf(&b, "- **Google Chrome / Chromium** — optional, used by chromedp when configured; not bundled with go-stock.\n\n")

	fmt.Fprintf(&b, "## Product vs Copyright License\n\n")
	fmt.Fprintf(&b, "- **Copyright license** for go-stock itself is defined in the root `LICENSE` file (currently GPL-3.0).\n")
	fmt.Fprintf(&b, "- **Product license keys** (`backend/license`) control Pro/Enterprise **features** only and do not replace third-party or copyright obligations.\n\n")

	fmt.Fprintf(&b, "## Regeneration\n\n")
	fmt.Fprintf(&b, "```powershell\nSet-Location %s\n./scripts/license/generate-inventory.ps1\n```\n", filepath.ToSlash(repoRoot))

	return b.String()
}

func writeGroupedGo(b *strings.Builder, rep goReport) {
	byLic := map[string][]string{}
	for _, e := range rep.Entries {
		if e.Module == "go-stock" || strings.HasPrefix(e.License, "PROJECT") {
			continue
		}
		lic := e.License
		if lic == "" {
			lic = "UNKNOWN"
		}
		line := fmt.Sprintf("`%s@%s`", e.Module, e.Version)
		if e.Direct {
			line += " (direct)"
		}
		byLic[lic] = append(byLic[lic], line)
	}
	lics := sortedKeys(byLic)
	for _, lic := range lics {
		fmt.Fprintf(b, "### %s (%d)\n\n", lic, len(byLic[lic]))
		sort.Strings(byLic[lic])
		for _, line := range byLic[lic] {
			fmt.Fprintf(b, "- %s\n", line)
		}
		b.WriteString("\n")
	}
}

func writeGroupedNPM(b *strings.Builder, pkgs map[string]npmPackage) {
	if len(pkgs) == 0 {
		fmt.Fprintf(b, "_Frontend inventory not generated yet. Run `scripts/license/generate-inventory.ps1`._\n\n")
		return
	}
	byLic := map[string][]string{}
	for name, p := range pkgs {
		lic := p.Licenses
		if lic == "" {
			lic = "UNKNOWN"
		}
		byLic[lic] = append(byLic[lic], fmt.Sprintf("`%s`", name))
	}
	for _, lic := range sortedKeys(byLic) {
		fmt.Fprintf(b, "### %s (%d)\n\n", lic, len(byLic[lic]))
		sort.Strings(byLic[lic])
		for _, line := range byLic[lic] {
			fmt.Fprintf(b, "- %s\n", line)
		}
		b.WriteString("\n")
	}
}

func sortedKeys(m map[string][]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
