// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {execution} from '../models';
import {strategyschema} from '../models';
import {models} from '../models';
import {data} from '../models';
import {strategyintent} from '../models';
import {riskreport} from '../models';
import {version} from '../models';
import {context} from '../models';
import {broker} from '../models';
import {papertrading} from '../models';
import {strategyexplain} from '../models';
import {main} from '../models';
import {lo} from '../models';
import {diagnostic} from '../models';
import {marketstate} from '../models';
import {research} from '../models';
import {job} from '../models';

export function AbortChatWithAgent():Promise<void>;

export function AbortSummaryStockNews():Promise<void>;

export function AccruePaperMarginInterest(arg1:number,arg2:string):Promise<execution.AccrualResult>;

export function ActivateStrategyRevision(arg1:string,arg2:string):Promise<strategyschema.WriteResult>;

export function AddAllStockInfo(arg1:models.AllStockInfo):Promise<string>;

export function AddCronTask(arg1:data.FollowedStock):Promise<any>;

export function AddGroup(arg1:data.Group):Promise<string>;

export function AddPrompt(arg1:models.Prompt):Promise<string>;

export function AddPromptTemplate(arg1:models.PromptTemplate):Promise<string>;

export function AddStockGroup(arg1:number,arg2:string):Promise<string>;

export function AddTradingRecord(arg1:data.TradingRecord):Promise<number>;

export function AnalyzeSentiment(arg1:string):Promise<models.SentimentResult>;

export function AnalyzeSentimentWithFreqWeight(arg1:string):Promise<Record<string, any>>;

export function ApproveStrategyIntent(arg1:string):Promise<strategyintent.WriteResult>;

export function BatchDeleteAIResponseResult(arg1:Array<number>):Promise<string>;

export function BatchDeleteAllStockInfo(arg1:Array<number>):Promise<string>;

export function BuildAdvancedRiskReport(arg1:string,arg2:string):Promise<riskreport.RiskReport>;

export function BuildCandidatePool(arg1:string):Promise<models.CandidatePool>;

export function BuildTradePlan(arg1:string):Promise<models.TradePlan>;

export function CalculateNextRunTime(arg1:string):Promise<string>;

export function CalculateNextRunTimes(arg1:string,arg2:number):Promise<Array<string>>;

export function ChatWithAgent(arg1:string,arg2:number,arg3:any,arg4:boolean,arg5:number,arg6:boolean):Promise<void>;

export function CheckFrequentTrading(arg1:string):Promise<Record<string, any>>;

export function CheckLocalUpdate():Promise<version.CheckResult>;

export function CheckSponsorCode(arg1:string):Promise<Record<string, any>>;

export function CheckStockBaseInfo(arg1:context.Context):Promise<void>;

export function CheckUpdate(arg1:number):Promise<void>;

export function ClsCalendar():Promise<Array<any>>;

export function ConfigurePaperMarginAccount(arg1:execution.AccountConfig):Promise<data.PaperMarginAccount>;

export function ConfirmBrokerOrderPlan(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number,arg6:string):Promise<broker.OrderResult>;

export function ConfirmTradingRecordDraft(arg1:number):Promise<void>;

export function CreateCronTask(arg1:models.CronTask):Promise<string>;

export function CreateStockStrategy(arg1:models.StockStrategy):Promise<string>;

export function CreateStrategyIntentDraft(arg1:strategyintent.CreateDraftRequest):Promise<strategyintent.WriteResult>;

export function CreateStrategySchemaDraft(arg1:strategyschema.CreateDraftRequest):Promise<strategyschema.WriteResult>;

export function DelPrompt(arg1:number):Promise<string>;

export function DeleteAIResponseResult(arg1:number):Promise<string>;

export function DeleteAiRecommendStocks(arg1:number):Promise<string>;

export function DeleteAllStockInfo(arg1:number):Promise<string>;

export function DeleteCronTask(arg1:number):Promise<string>;

export function DeletePromptTemplate(arg1:number):Promise<string>;

export function DeleteStockChangeHistory(arg1:number):Promise<string>;

export function DeleteStockStrategy(arg1:number):Promise<string>;

export function DeleteTradingRecord(arg1:number):Promise<void>;

export function DevGetPaperSimAccount():Promise<papertrading.DevAccountResult>;

export function DevResetPaperSimAccount(arg1:number):Promise<papertrading.DevAccountResult>;

export function DevSetPaperSimCash(arg1:number):Promise<papertrading.DevAccountResult>;

export function EMDictCode(arg1:string):Promise<Array<any>>;

export function EnableCronTask(arg1:number,arg2:boolean):Promise<string>;

export function ExecuteCronTaskNow(arg1:number):Promise<string>;

export function ExplainStrategyPlanItem(arg1:string,arg2:number,arg3:number,arg4:boolean):Promise<strategyexplain.Explanation>;

export function ExplainStrategySnapshot(arg1:string,arg2:string,arg3:boolean):Promise<strategyexplain.Explanation>;

export function ExportConfig():Promise<string>;

export function ExportDailyPilotReport():Promise<string>;

export function ExportDiagnosticBundle():Promise<string>;

export function ExportDiagnosticJSON():Promise<string>;

export function FeatureGateAllow(arg1:string,arg2:string):Promise<boolean>;

export function FeatureGateCanAccess(arg1:string,arg2:string):Promise<main.FeatureGateDecisionDTO>;

export function FeatureGateEvaluateAll(arg1:string):Promise<Array<main.FeatureGateDecisionDTO>>;

export function FeatureGateKnownFeatures():Promise<Array<string>>;

export function FetchAiModels(arg1:string,arg2:string):Promise<Array<string>>;

export function FillPaperOrder(arg1:number,arg2:number):Promise<void>;

export function Follow(arg1:string):Promise<string>;

export function FollowFund(arg1:string):Promise<string>;

export function GetAIResponseResult(arg1:string):Promise<models.AIResponseResult>;

export function GetAIResponseResultList(arg1:models.AIResponseResultQuery):Promise<models.AIResponseResultPageData>;

export function GetAiAssistantSession(arg1:string):Promise<models.AiAssistantSessionResp>;

export function GetAiConfigs():Promise<Array<data.AIConfig>>;

export function GetAiRecommendStocksList(arg1:models.AiRecommendStocksQuery):Promise<models.AiRecommendStocksPageData>;

export function GetAllConcepts():Promise<Array<string>>;

export function GetAllIndustries():Promise<Array<string>>;

export function GetAllMarkets():Promise<Array<string>>;

export function GetAllStockChangesWithPaging(arg1:number):Promise<data.StockChangesResponse>;

export function GetAllStockInfoById(arg1:number):Promise<models.AllStockInfo>;

export function GetAllStockInfoList(arg1:data.AllStockInfoQuery):Promise<data.AllStockInfoPageData>;

export function GetAllStocks(arg1:number,arg2:number,arg3:string,arg4:string,arg5:string,arg6:string,arg7:models.TechnicalIndicators):Promise<models.AllStocksResp>;

export function GetConfig():Promise<data.SettingConfig>;

export function GetCronTaskByID(arg1:number):Promise<models.CronTask>;

export function GetCronTaskList(arg1:models.CronTaskQuery):Promise<models.CronTaskPageResp>;

export function GetCronTaskTypes():Promise<Array<lo.Tuple2_string_string_>>;

export function GetCurrentMarketState():Promise<string>;

export function GetDailyTradingStatus():Promise<data.DailyTradingStatus>;

export function GetDiagnosticInfo():Promise<diagnostic.Info>;

export function GetEffectiveSponsorVip():Promise<Record<string, any>>;

export function GetFollowList(arg1:number):Promise<any>;

export function GetFollowRealtimeList(arg1:number):Promise<any>;

export function GetFollowedFund():Promise<Array<data.FollowedFund>>;

export function GetGroupList():Promise<Array<data.Group>>;

export function GetGroupStockList(arg1:number):Promise<Array<data.GroupStock>>;

export function GetHotConceptPlates(arg1:number):Promise<Array<Record<string, any>>>;

export function GetHotIndustryPlates(arg1:number):Promise<Array<Record<string, any>>>;

export function GetHotStrategy():Promise<Record<string, any>>;

export function GetIndustryMoneyRankSina(arg1:string,arg2:string):Promise<Array<Record<string, any>>>;

export function GetIndustryRank(arg1:string,arg2:number):Promise<Array<any>>;

export function GetLatestSignalScanSnapshot(arg1:string,arg2:string):Promise<models.SignalScanSnapshot>;

export function GetLatestSignalScanSnapshotByStrategy(arg1:string,arg2:string,arg3:string):Promise<models.SignalScanSnapshot>;

export function GetLatestSignalScanTask():Promise<data.SignalScanTaskView>;

export function GetLoadingProgress():Promise<main.LoadingProgress>;

export function GetMarketSessionSnapshot():Promise<marketstate.Snapshot>;

export function GetMoneyRankSina(arg1:string):Promise<Array<Record<string, any>>>;

export function GetPaperAccountSnapshot(arg1:number):Promise<data.PaperAccountSnapshot>;

export function GetPaperMarginSnapshot(arg1:number,arg2:Array<execution.PositionMark>):Promise<execution.Snapshot>;

export function GetPaperOpenBuyConfig():Promise<data.PaperOpenBuyConfig>;

export function GetPaperOpenBuyStatus():Promise<data.PaperOpenBuyStatus>;

export function GetPaperOrderHealth(arg1:string):Promise<data.PaperOrderHealthReport>;

export function GetPromptTemplateList(arg1:models.PromptTemplateQuery):Promise<models.PromptTemplatePageData>;

export function GetPromptTemplates(arg1:string,arg2:string):Promise<any>;

export function GetReleaseIdentity():Promise<version.VersionInfo>;

export function GetResearchCandidate(arg1:string):Promise<research.DetailResult>;

export function GetResearchExplain(arg1:string):Promise<research.Explain>;

export function GetSignalScanSnapshotDetail(arg1:number):Promise<models.SignalScanResultPayload>;

export function GetSignalScanTask(arg1:string):Promise<data.SignalScanTaskView>;

export function GetSponsorInfo():Promise<Record<string, any>>;

export function GetStockChangeHistory(arg1:models.StockChangeHistoryQuery):Promise<models.StockChangeHistoryPageData>;

export function GetStockChanges(arg1:Array<number>,arg2:number,arg3:number):Promise<data.StockChangesResponse>;

export function GetStockCommonKLine(arg1:string,arg2:string,arg3:number):Promise<any>;

export function GetStockEastMoneyKLine(arg1:string,arg2:string,arg3:string,arg4:number):Promise<any>;

export function GetStockEastMoneyKLinePage(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string):Promise<any>;

export function GetStockKLine(arg1:string,arg2:string,arg3:number):Promise<any>;

export function GetStockList(arg1:string):Promise<Array<data.StockBasic>>;

export function GetStockMinutePriceLineData(arg1:string,arg2:string):Promise<Record<string, any>>;

export function GetStockMoneyTrendByDay(arg1:string,arg2:number):Promise<Array<Record<string, any>>>;

export function GetStockRealTimePrice(arg1:string):Promise<Record<string, any>>;

export function GetStockStrategyByID(arg1:number):Promise<models.StockStrategy>;

export function GetStockStrategyList(arg1:models.StockStrategyQuery):Promise<models.StockStrategyPageResp>;

export function GetStockStrategyRunDetail(arg1:number):Promise<models.StockStrategyRunView>;

export function GetStockStrategyRunList(arg1:models.StockStrategyRunQuery):Promise<models.StockStrategyRunPageResp>;

export function GetStockStrategySummary(arg1:number):Promise<string>;

export function GetStrategyIntent(arg1:string):Promise<strategyintent.Intent>;

export function GetStrategyPerformance():Promise<Array<data.StrategyPerformanceRow>>;

export function GetStrategyRevision(arg1:string,arg2:string):Promise<strategyschema.Revision>;

export function GetStrategySchema(arg1:string):Promise<strategyschema.DetailResult>;

export function GetTelegraphList(arg1:string):Promise<any>;

export function GetTimezone():Promise<Record<string, any>>;

export function GetTodayTradeAnalysis():Promise<data.TradePlanAnalysis>;

export function GetTodayTradePlan():Promise<models.TradePlan>;

export function GetTradePlanAnalysis(arg1:string):Promise<data.TradePlanAnalysis>;

export function GetTradingRecordById(arg1:number):Promise<data.TradingRecord>;

export function GetTradingRecordList(arg1:data.TradingRecordListQuery):Promise<data.TradingRecordPageData>;

export function GetTradingRecordStatistics():Promise<data.TradingRecordStatistics>;

export function GetVersionInfo():Promise<models.VersionInfo>;

export function GetfundList(arg1:string):Promise<Array<data.FundBasic>>;

export function GlobalStockIndexes():Promise<Record<string, any>>;

export function GlobalStockIndexesReadable():Promise<string>;

export function Greet(arg1:string):Promise<data.StockInfo>;

export function HotEvent(arg1:number):Promise<any>;

export function HotStock(arg1:string):Promise<any>;

export function HotTopic(arg1:number):Promise<Array<any>>;

export function IndustryResearchReport(arg1:string):Promise<Array<any>>;

export function InitAfterClosePlanJobs():Promise<void>;

export function InitCronTasks():Promise<void>;

export function InitJobRuntimeReliability():Promise<void>;

export function InitMorningPreparationJobs():Promise<void>;

export function InitPaperMarginDayJobs():Promise<void>;

export function InitPaperOpenBuyJobs():Promise<void>;

export function InitPaperTradingJobs():Promise<void>;

export function InitStockStrategies():Promise<void>;

export function InitTradingAutomationJobs():Promise<void>;

export function InitializeGroupSort():Promise<boolean>;

export function InvestCalendarTimeLine(arg1:string):Promise<Array<any>>;

export function IsSignalScanRunning():Promise<boolean>;

export function IsWatchlistPricePollingPaused():Promise<boolean>;

export function JobRuntimeDetectMissed():Promise<Array<job.MissedInfo>>;

export function JobRuntimeList():Promise<Array<job.RuntimeState>>;

export function JobRuntimeRecords(arg1:string,arg2:number):Promise<Array<job.ExecutionRecord>>;

export function ListResearchCandidates(arg1:string,arg2:number):Promise<research.ListResult>;

export function ListResearchSnapshotCandidates(arg1:number):Promise<models.ResearchSnapshotCandidateList>;

export function ListSignalScanSnapshots(arg1:models.SignalScanSnapshotQuery):Promise<models.SignalScanSnapshotPageResp>;

export function ListStrategyIntents():Promise<strategyintent.ListResult>;

export function ListStrategyRevisions(arg1:string):Promise<strategyschema.RevisionListResult>;

export function ListStrategySchemas():Promise<strategyschema.ListResult>;

export function LongTigerRank(arg1:string):Promise<any>;

export function MarketCanExecute():Promise<boolean>;

export function MarketCanGeneratePlan():Promise<boolean>;

export function NewChatStream(arg1:string,arg2:string,arg3:string,arg4:number,arg5:any,arg6:boolean,arg7:boolean):Promise<void>;

export function NewsPush(arg1:any):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function ParseSignalScanSnapshotPayload(arg1:models.SignalScanSnapshot):Promise<models.SignalScanResultPayload>;

export function PersistPhase9C3ObservationSnapshot(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function ReFleshTelegraphList(arg1:string):Promise<any>;

export function RefreshWatchlistPricesNow():Promise<void>;

export function RemoveGroup(arg1:number):Promise<string>;

export function RemoveStockGroup(arg1:string,arg2:string,arg3:number):Promise<string>;

export function ResetPaperAccount(arg1:number):Promise<data.PaperAccount>;

export function RunDailyCandidateAndPlan(arg1:string):Promise<Record<string, any>>;

export function RunPaperMarginRiskScan(arg1:number,arg2:Array<execution.PositionMark>):Promise<Array<data.PaperMarginRiskEvent>>;

export function RunPaperOpenBuyOnce():Promise<data.PaperOpenBuyResult>;

export function RunPaperOpenPrepare():Promise<data.PaperOpenBuyResult>;

export function RunSignalScanSnapshot(arg1:string,arg2:string,arg3:string,arg4:string):Promise<models.SignalScanSnapshot>;

export function RunStockStrategy(arg1:number):Promise<models.StockStrategyRunView>;

export function SaveAIResponseResult(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number):Promise<void>;

export function SaveAiAssistantSession(arg1:string,arg2:Array<models.AiAssistantMessage>):Promise<void>;

export function SaveAsMarkdown(arg1:string,arg2:string):Promise<string>;

export function SaveImage(arg1:string,arg2:string):Promise<string>;

export function SaveStockChangesToHistory(arg1:Array<number>):Promise<string>;

export function SaveWordFile(arg1:string,arg2:string):Promise<string>;

export function ScanPaperMarginRisk(arg1:number,arg2:Array<execution.PositionMark>):Promise<Array<data.PaperMarginRiskEvent>>;

export function SearchCronTasks(arg1:string):Promise<Array<models.CronTask>>;

export function SearchStock(arg1:string):Promise<Record<string, any>>;

export function SendDingDingMessage(arg1:string,arg2:string):Promise<string>;

export function SendDingDingMessageByType(arg1:string,arg2:string,arg3:number):Promise<string>;

export function SetAlarmChangePercent(arg1:number,arg2:number,arg3:string):Promise<string>;

export function SetCostPriceAndVolume(arg1:string,arg2:number,arg3:number):Promise<string>;

export function SetPaperMarkPrice(arg1:number,arg2:string,arg3:number):Promise<void>;

export function SetPaperOpenBuyConfig(arg1:data.PaperOpenBuyConfig):Promise<data.PaperOpenBuyConfig>;

export function SetStockAICron(arg1:string,arg2:string):Promise<void>;

export function SetStockSort(arg1:number,arg2:string):Promise<void>;

export function SetTradingPrice(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number):Promise<string>;

export function SetWatchlistPricePollingPaused(arg1:boolean):Promise<void>;

export function SettlePaperSellable(arg1:number):Promise<void>;

export function ShareAnalysis(arg1:string,arg2:string):Promise<string>;

export function ShareText(arg1:string,arg2:string):Promise<string>;

export function StartSignalScanSnapshot(arg1:string,arg2:string,arg3:string,arg4:string):Promise<data.SignalScanTaskView>;

export function StockNotice(arg1:string):Promise<Array<any>>;

export function StockResearchReport(arg1:string):Promise<Array<any>>;

export function SubmitPaperMarginOrder(arg1:execution.SubmitRequest):Promise<data.PaperMarginOrder>;

export function SubmitPaperOrder(arg1:data.PaperSubmitOrderReq):Promise<data.PaperOrder>;

export function SubmitStrategyIntent(arg1:string):Promise<strategyintent.WriteResult>;

export function SubmitStrategyRevision(arg1:string,arg2:string):Promise<strategyschema.WriteResult>;

export function SummaryStockNews(arg1:string,arg2:number,arg3:any,arg4:boolean,arg5:boolean,arg6:string,arg7:string):Promise<void>;

export function UnFollow(arg1:string):Promise<string>;

export function UnFollowFund(arg1:string):Promise<string>;

export function UpdateAiRecommendStocksAlert(arg1:number,arg2:boolean):Promise<string>;

export function UpdateConfig(arg1:data.SettingConfig):Promise<string>;

export function UpdateCronTask(arg1:models.CronTask):Promise<string>;

export function UpdateGroupSort(arg1:number,arg2:number):Promise<boolean>;

export function UpdatePromptTemplate(arg1:models.PromptTemplate):Promise<string>;

export function UpdateResearchCandidate(arg1:string,arg2:string,arg3:string,arg4:Array<string>,arg5:boolean,arg6:boolean,arg7:boolean):Promise<research.DetailResult>;

export function UpdateResearchExplain(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:boolean,arg8:boolean,arg9:boolean,arg10:boolean):Promise<research.Explain>;

export function UpdateStockStrategy(arg1:models.StockStrategy):Promise<string>;

export function UpdateStrategyIntentDraft(arg1:string,arg2:strategyintent.UpdateDraftRequest):Promise<strategyintent.WriteResult>;

export function UpdateStrategySchemaDraft(arg1:string,arg2:string,arg3:strategyschema.UpdateDraftRequest):Promise<strategyschema.WriteResult>;

export function UpdateTradingRecord(arg1:data.TradingRecord):Promise<void>;

export function UpsertBuySignalDraft(arg1:data.TradingRecord):Promise<number>;

export function UpsertPaperBorrowPool(arg1:data.PaperBorrowPool):Promise<data.PaperBorrowPool>;

export function UpsertSellSignalDraft(arg1:data.TradingRecord):Promise<number>;

export function ValidateCronExpr(arg1:string):Promise<string>;
